--
--
-- Winter Resort Simulator - Modding SDK
-- Data tables for default content
--
--
-- Copyright (C) HR Innoways GmbH. All Rights Reserved.
--
-- Please view the license file in the root directory. All scripts
-- contained in the Winter Resort Simulator Modding SDK may only be
-- used as specified in that license file.
--
--

ModLoader.addContent("support", {
	contentName		= "mgd_supports",
	title			= "Monocable shaft support",
	fullDesc		= "Supports for monocable ropeways",
	class			= ModularSupportKit,

	shafts				= {
		{	height		= 3.5,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0350",	interface="0",		},
		{	height		= 4.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0400",	interface="0",		},
		{	height		= 4.5,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0450",	interface="0",		},
		{	height		= 5.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0500",	interface="0",		},
		{	height		= 5.5,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0550",	interface="0",		},
		{	height		= 6.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0600",	interface="0",		},
		{	height		= 6.5,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0650",	interface="0",		},
		{	height		= 7.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0700",	interface="0",		},
		{	height		= 7.5,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0750",	interface="0",		},
		{	height		= 8.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0800",	interface="0",		},
		{	height		= 8.5,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0850",	interface="0",		},
		{	height		= 9.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0900",	interface="0",		},
		{	height		= 9.5,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_0950",	interface="0",		},
		{	height		= 10.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_1000",	interface="0",		},
		{	height		= 11.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_1100",	interface="0",		},
		{	height		= 12.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_1200",	interface="0",		},
		{	height		= 13.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_1300",	interface="0",		},
		{	height		= 14.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_1400",	interface="0",		},
		{	height		= 15.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_1500",	interface="0",		},
		{	height		= 16.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_1600",	interface="0",		},
		{	height		= 17.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_1700",	interface="0",		},
		{	height		= 18.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_1800",	interface="0",		},
		{	height		= 19.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_1900",	interface="0",		},
		{	height		= 20.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_2000",	interface="0",		},
		{	height		= 21.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_2100",	interface="0",		},
		{	height		= 22.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_2200",	interface="0",		},
		{	height		= 23.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_2300",	interface="0",		},
		{	height		= 24.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_2400",	interface="0",		},
		{	height		= 25.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_2500",	interface="0",		},
		{	height		= 26.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_2600",	interface="0",		},
		{	height		= 27.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_2700",	interface="0",		},
		{	height		= 28.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_2800",	interface="0",		},
		{	height		= 29.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_2900",	interface="0",		},
		{	height		= 30.0,	prefab	= "$ropeways/D-Line/supports/Schaefte>DM_Schaft_3000",	interface="0",		},
	},
	yokes				= {
		{
			name		= "TR_schwach",
			variations	= {
				{
					gauge	= 5.2,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>52_schwach",
					leftSheaveIndex		= "52_RobaInterface0",
					rightSheaveIndex	= "52_RobaInterface1",
					--platforms			= {"52_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 5.5,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>55_schwach",
					leftSheaveIndex		= "55_RobaInterface0",
					rightSheaveIndex	= "55_RobaInterface1",
					--platforms			= {"55_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 6.2,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>62_schwach",
					leftSheaveIndex		= "62_RobaInterface0",
					rightSheaveIndex	= "62_RobaInterface1",
					--platforms			= {"62_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 6.4,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>64_schwach",
					leftSheaveIndex		= "64_RobaInterface0",
					rightSheaveIndex	= "64_RobaInterface1",
					--platforms			= {"64_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 6.7,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>67_schwach",
					leftSheaveIndex		= "67_RobaInterface0",
					rightSheaveIndex	= "67_RobaInterface1",
					--platforms			= {"67_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 7.2,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>72_schwach",
					leftSheaveIndex		= "72_RobaInterface0",
					rightSheaveIndex	= "72_RobaInterface1",
					--platforms			= {"72_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 7.7,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>77_schwach",
					leftSheaveIndex		= "77_RobaInterface0",
					rightSheaveIndex	= "77_RobaInterface1",
					--platforms			= {"77_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
			}
		},
		{
			name		= "TR_stark",
			variations	= {
				{
					gauge	= 5.2,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>52_stark",
					leftSheaveIndex		= "52_RobaInterface0",
					rightSheaveIndex	= "52_RobaInterface1",
					--platforms			= {"52_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 5.5,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>55_stark",
					leftSheaveIndex		= "55_RobaInterface0",
					rightSheaveIndex	= "55_RobaInterface1",
					--platforms			= {"55_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 6.2,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>62_stark",
					leftSheaveIndex		= "62_RobaInterface0",
					rightSheaveIndex	= "62_RobaInterface1",
					--platforms			= {"62_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 6.4,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>64_stark",
					leftSheaveIndex		= "64_RobaInterface0",
					rightSheaveIndex	= "64_RobaInterface1",
					--platforms			= {"64_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 6.7,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>67_stark",
					leftSheaveIndex		= "67_RobaInterface0",
					rightSheaveIndex	= "67_RobaInterface1",
					--platforms			= {"67_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 7.2,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>72_stark",
					leftSheaveIndex		= "72_RobaInterface0",
					rightSheaveIndex	= "72_RobaInterface1",
					--platforms			= {"72_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 7.7,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>77_stark",
					leftSheaveIndex		= "77_RobaInterface0",
					rightSheaveIndex	= "77_RobaInterface1",
					--platforms			= {"77_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
			}
		},
		{
			name		= "WL",
			variations	= {
				{
					gauge	= 5.2,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>52_WL",
					leftSheaveIndex		= "52_RobaInterface0",
					rightSheaveIndex	= "52_RobaInterface1",
					--platforms			= {"52_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 5.5,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>55_WL",
					leftSheaveIndex		= "55_RobaInterface0",
					rightSheaveIndex	= "55_RobaInterface1",
					--platforms			= {"55_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 6.2,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>62_WL",
					leftSheaveIndex		= "62_RobaInterface0",
					rightSheaveIndex	= "62_RobaInterface1",
					--platforms			= {"62_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 6.4,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>64_WL",
					leftSheaveIndex		= "64_RobaInterface0",
					rightSheaveIndex	= "64_RobaInterface1",
					--platforms			= {"64_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 6.7,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>67_WL",
					leftSheaveIndex		= "67_RobaInterface0",
					rightSheaveIndex	= "67_RobaInterface1",
					--platforms			= {"67_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 7.2,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>72_WL",
					leftSheaveIndex		= "72_RobaInterface0",
					rightSheaveIndex	= "72_RobaInterface1",
					--platforms			= {"72_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
				{
					gauge	= 7.7,
					prefab	= "$ropeways/D-Line/supports/Joch_neu>77_WL",
					leftSheaveIndex		= "77_RobaInterface0",
					rightSheaveIndex	= "77_RobaInterface1",
					--platforms			= {"77_Wartungskoerbe",},
					idleSound			= "sound",
					announcementSpeaker	= "",
					supportNoLabels		= { "Number1/Text", "Number2/Text" },
				},
			}
		},
	},

	sheaveBatteries		= {
		{	prefab		= "$ropeways/D-Line/supports/Robas_neu>Roba_TR_04",		minForce	= 4,		maxForce = 31,		yoke = "TR_schwach"	},
		{	prefab		= "$ropeways/D-Line/supports/Robas_neu>Roba_TR_06",		minForce	= 5,		maxForce = 47,		yoke = "TR_schwach"	},
		{	prefab		= "$ropeways/D-Line/supports/Robas_neu>Roba_TR_08",		minForce	= 7,		maxForce = 62,		yoke = "TR_schwach"	},
		{	prefab		= "$ropeways/D-Line/supports/Robas_neu>Roba_TR_12",		minForce	= 9,		maxForce = 94,		yoke = "TR_schwach"	},
		{	prefab		= "$ropeways/D-Line/supports/Robas_neu>Roba_TR_16",		minForce	= 11,		maxForce = 135,		yoke = "TR_stark"	},
		{	prefab		= "$ropeways/D-Line/supports/Robas_neu>Roba_NH_06",		minForce	= -35,		maxForce = -5,		yoke = "TR_schwach"	},
		{	prefab		= "$ropeways/D-Line/supports/Robas_neu>Roba_NH_08",		minForce	= -45,		maxForce = -10,		yoke = "TR_schwach"	},
		{	prefab		= "$ropeways/D-Line/supports/Robas_neu>Roba_NH_12",		minForce	= -85,		maxForce = -20,		yoke = "TR_schwach"	},
		{	prefab		= "$ropeways/D-Line/supports/Robas_neu>Roba_NH_16",		minForce	= -125,		maxForce = -30,		yoke = "TR_schwach"	},
		{	prefab		= "$ropeways/D-Line/supports/Robas_neu>Roba_WL_04",		minForce	= -22,		maxForce = 22,		yoke = "WL"			},
		{	prefab		= "$ropeways/D-Line/supports/Robas_neu>Roba_WL_08",		minForce	= -45,		maxForce = 45,		yoke = "WL"			},
	},

	sheaveBatteryDetails		= {
		{ --TR04
			prefab				= "$ropeways/D-Line/supports/Robas_neu>Roba_TR_04",
			balancers			= {
				{	index		= "Wippe_04T_b",																averageScale	= 1			},
				{	index		= "Wippe_04T_b/Wippe_02T",						deflectionScale	= -0.25										},
				{	index		= "Wippe_04T_b/Wippe_02T (1)",					deflectionScale	=  0.25										},
				
				{	index		= "Wartungspodest_Mittel_3/Podeste_3P_LI", 		deflectionScale	=  0.5,			averageScale	= 1			},
				{	index		= "Wartungspodest_Mittel_3/Podeste_3P_RE", 		deflectionScale	=  0.5,			averageScale	= -1		},
			},
			marshallerA			= "MarshallerA",
			marshallers			= { 
				"Wippe_04T_b/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_04T_b/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_04T_b/Wippe_02T (1)/Wippe_02T_MarshallerC_01", 
				"Wippe_04T_b/Wippe_02T (1)/Wippe_02T_MarshallerC_02", 
			},
			animated			= {
				{	index		= "Wippe_04T_b/Wippe_02T/Rolle",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_04T_b/Wippe_02T/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_04T_b/Wippe_02T (1)/Rolle",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_04T_b/Wippe_02T (1)/Rolle (1)",	axis = 1,	diam	= 0.45,		scale	= 1.0 },
			}, 
			platforms			= { 
					"Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (1)/Podest_lang_BK", 
					"Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (2)/Podest_lang_BK", 
					"Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (3)/Podest_lang_BK", 
					
					"Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (1)/Podest_lang_BK", 
					"Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (2)/Podest_lang_BK", 
					"Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (3)/Podest_lang_BK", 
					
					"Wartungspodest_Mittel_3/Podest_lang_BK", 
			},
			
			onlyActiveWhenRight	= { "Wartungspodest_Mittel_3/Halter_mittel/Leiter_mittel", 		},
			onlyActiveWhenLeft	= { "Wartungspodest_Mittel_3/Halter_mittel/Leiter_mittel (1)", 	},
			
			rotateToTarget		= {
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Strebenhalter_oben/Streben_LI", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_LI/Strebe_3P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Mittel_3/Podeste_3P_LI/Strebe_3P_1/Strebe_3P_2", 
					pistonIndex 		= "Wartungspodest_Mittel_3/Podeste_3P_LI/Strebe_3P_1/Strebe_3P_3",
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Strebenhalter_oben/Streben_RE", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_RE/Strebe_3P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Mittel_3/Podeste_3P_RE/Strebe_3P_1/Strebe_3P_2", 
					pistonIndex 		= "Wartungspodest_Mittel_3/Podeste_3P_RE/Strebe_3P_1/Strebe_3P_3",
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (1)/Podest_lang_BK/Gelaender_Li/Target_O", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (3)/Podest_lang_BK/Gelaender_Be/Stange_1300", 
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (1)/Podest_lang_BK/Gelaender_Li/Target_U", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (3)/Podest_lang_BK/Gelaender_Be/Stange_1300 (1)", 
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (1)/Podest_lang_BK/Gelaender_Re/Target_O", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (3)/Podest_lang_BK/Gelaender_Be/Stange_1300", 
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (1)/Podest_lang_BK/Gelaender_Re/Target_U", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (3)/Podest_lang_BK/Gelaender_Be/Stange_1300 (1)", 
				},
			},
		},
		{ --TR06
			prefab				= "$ropeways/D-Line/supports/Robas_neu>Roba_TR_06",
			balancers			= {				
				{	index		= "Wippe_06T_b",																averageScale	= 1			},
				{	index		= "Wippe_06T_b/Wippe_04T",						deflectionScale	= -0.28										},
				{	index		= "Wippe_06T_b/Wippe_04T/Wippe_02T",			deflectionScale	= -0.24										},
				{	index		= "Wippe_06T_b/Wippe_04T/Wippe_02T (1)",		deflectionScale	= 0.24										},
				{	index		= "Wippe_06T_b/Wippe_02T",						deflectionScale	= 0.24										},
				
				{	index		= "Wartungspodest_Mittel_3/Podeste_3P_LI", 		deflectionScale	=  0.5,			averageScale	= 1			},
				{	index		= "Wartungspodest_Mittel_3/Podeste_3P_RE", 		deflectionScale	=  0.5,			averageScale	= -1		},
			}, 
			marshallerA			= "MarshallerA",
			marshallers			= { 
				"Wippe_06T_b/Wippe_04T/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_06T_b/Wippe_04T/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_06T_b/Wippe_04T/Wippe_02T (1)/Wippe_02T_MarshallerC_01", 
				"Wippe_06T_b/Wippe_04T/Wippe_02T (1)/Wippe_02T_MarshallerC_02", 
				"Wippe_06T_b/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_06T_b/Wippe_02T/Wippe_02T_MarshallerC_02" },
			animated			= {
				{	index		= "Wippe_06T_b/Wippe_04T/Wippe_02T/Rolle",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_06T_b/Wippe_04T/Wippe_02T/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_06T_b/Wippe_04T/Wippe_02T (1)/Rolle",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_06T_b/Wippe_04T/Wippe_02T (1)/Rolle (1)",	axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_06T_b/Wippe_02T/Rolle",					axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_06T_b/Wippe_02T/Rolle (1)",				axis = 1,	diam	= 0.45,		scale	= 1.0 },
			}, 
			platforms			= { 
					"Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (1)/Podest_lang_BK", 
					"Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (2)/Podest_lang_BK", 
					"Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (3)/Podest_lang_BK", 
					
					"Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (1)/Podest_lang_BK", 
					"Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (2)/Podest_lang_BK", 
					"Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (3)/Podest_lang_BK", 
					
					"Wartungspodest_Mittel_3/Podest_lang_BK", 
			},
			
			onlyActiveWhenRight	= { "Wartungspodest_Mittel_3/Halter_mittel/Leiter_mittel", 		},
			onlyActiveWhenLeft	= { "Wartungspodest_Mittel_3/Halter_mittel/Leiter_mittel (1)", 	},
			
			rotateToTarget		= {
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Strebenhalter_oben/Streben_LI", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_LI/Strebe_3P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Mittel_3/Podeste_3P_LI/Strebe_3P_1/Strebe_3P_2", 
					pistonIndex 		= "Wartungspodest_Mittel_3/Podeste_3P_LI/Strebe_3P_1/Strebe_3P_3",
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Strebenhalter_oben/Streben_RE", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_RE/Strebe_3P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Mittel_3/Podeste_3P_RE/Strebe_3P_1/Strebe_3P_2", 
					pistonIndex 		= "Wartungspodest_Mittel_3/Podeste_3P_RE/Strebe_3P_1/Strebe_3P_3",
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (1)/Podest_lang_BK/Gelaender_Li/Target_O", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (3)/Podest_lang_BK/Gelaender_Be/Stange_1300", 
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (1)/Podest_lang_BK/Gelaender_Li/Target_U", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (3)/Podest_lang_BK/Gelaender_Be/Stange_1300 (1)", 
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (1)/Podest_lang_BK/Gelaender_Re/Target_O", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (3)/Podest_lang_BK/Gelaender_Be/Stange_1300", 
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (1)/Podest_lang_BK/Gelaender_Re/Target_U", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (3)/Podest_lang_BK/Gelaender_Be/Stange_1300 (1)", 
				},
			},
		},
		{ --TR08
			prefab				= "$ropeways/D-Line/supports/Robas_neu>Roba_TR_08", 
			balancers			= {
				{	index		= "Wippe_08T_s",																	averageScale	= 1			},
				{	index		= "Wippe_08T_s/Wippe_04T",							deflectionScale	= -0.25										},
				{	index		= "Wippe_08T_s/Wippe_04T (1)",						deflectionScale	=  0.25										},
				{	index		= "Wippe_08T_s/Wippe_04T/Wippe_02T",				deflectionScale	=  -0.125									},
				{	index		= "Wippe_08T_s/Wippe_04T/Wippe_02T (1)",			deflectionScale	=  0.125									},
				{	index		= "Wippe_08T_s/Wippe_04T (1)/Wippe_02T",			deflectionScale	=  -0.125									},
				{	index		= "Wippe_08T_s/Wippe_04T (1)/Wippe_02T (1)",		deflectionScale	=  0.125									},
				
				{	index		= "Wartungspodest_Mittel_4/Podeste_4P_LI", 			deflectionScale	=  0.5,			averageScale	= 1			},
				{	index		= "Wartungspodest_Mittel_4/Podeste_4P_RE", 			deflectionScale	=  0.5,			averageScale	= -1		},
			},
			marshallerA			= "MarshallerA",
			marshallers			= { 
					"Wippe_08T_s/Wippe_04T/Wippe_02T/Wippe_02T_MarshallerC_01",
					"Wippe_08T_s/Wippe_04T/Wippe_02T/Wippe_02T_MarshallerC_02", 
					"Wippe_08T_s/Wippe_04T/Wippe_02T (1)/Wippe_02T_MarshallerC_01",
					"Wippe_08T_s/Wippe_04T/Wippe_02T (1)/Wippe_02T_MarshallerC_02", 
					"Wippe_08T_s/Wippe_04T (1)/Wippe_02T/Wippe_02T_MarshallerC_01",
					"Wippe_08T_s/Wippe_04T (1)/Wippe_02T/Wippe_02T_MarshallerC_02", 
					"Wippe_08T_s/Wippe_04T (1)/Wippe_02T (1)/Wippe_02T_MarshallerC_01",
					"Wippe_08T_s/Wippe_04T (1)/Wippe_02T (1)/Wippe_02T_MarshallerC_02", 
			},
			animated			= {
				{	index		= "Wippe_08T_s/Wippe_04T/Wippe_02T/Rolle",				axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_08T_s/Wippe_04T/Wippe_02T/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_08T_s/Wippe_04T/Wippe_02T (1)/Rolle",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_08T_s/Wippe_04T/Wippe_02T (1)/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_08T_s/Wippe_04T (1)/Wippe_02T/Rolle",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_08T_s/Wippe_04T (1)/Wippe_02T/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_08T_s/Wippe_04T (1)/Wippe_02T (1)/Rolle",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_08T_s/Wippe_04T (1)/Wippe_02T (1)/Rolle (1)",	axis = 1,	diam	= 0.45,		scale	= 1.0 },
			},
			platforms			= { 
					"Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_kurz_LI (1)/Podest_kurz_BK", 
					"Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_kurz_LI (2)/Podest_kurz_BK", 
					"Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_lang_LI (3)/Podest_lang_BK", 
					"Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_lang_LI (4)/Podest_lang_BK", 
					
					"Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_kurz_RE (1)/Podest_kurz_BK", 
					"Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_kurz_RE (2)/Podest_kurz_BK", 
					"Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_lang_RE (3)/Podest_lang_BK", 
					"Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_lang_RE (4)/Podest_lang_BK", 
					
					"Wartungspodest_Mittel_4/Podest_kurz_BK", 
			},
			
			onlyActiveWhenRight	= { "Wartungspodest_Mittel_4/Halter_mittel/Leiter_mittel", 		},
			onlyActiveWhenLeft	= { "Wartungspodest_Mittel_4/Halter_mittel/Leiter_mittel (1)", 	},
			
			rotateToTarget		= {
				{	
					targetIndex			= "Wartungspodest_Mittel_4/Strebenhalter_oben/Streben_LI", 
					index				= "Wartungspodest_Mittel_4/Podeste_4P_LI/Strebe_4P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Mittel_4/Podeste_4P_LI/Strebe_4P_1/Strebe_4P_2", 
					pistonIndex 		= "Wartungspodest_Mittel_4/Podeste_4P_LI/Strebe_4P_1/Strebe_4P_3",
				},                                               
				{	                                             
					targetIndex			= "Wartungspodest_Mittel_4/Strebenhalter_oben/Streben_RE", 
					index				= "Wartungspodest_Mittel_4/Podeste_4P_RE/Strebe_4P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Mittel_4/Podeste_4P_RE/Strebe_4P_1/Strebe_4P_2", 
					pistonIndex 		= "Wartungspodest_Mittel_4/Podeste_4P_RE/Strebe_4P_1/Strebe_4P_3",
				},                                               
				{	                                          
					targetIndex			= "Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_O", 
					index				= "Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_lang_LI (4)/Podest_lang_BK/Gelaender_Be/Stange_1950", 
				},                                                                 
				{	                                                            
					targetIndex			= "Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_U", 
					index				= "Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_lang_LI (4)/Podest_lang_BK/Gelaender_Be/Stange_1950 (1)", 
				},                                                             
				{	                                                                  
					targetIndex			= "Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_O", 
					index				= "Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_lang_RE (4)/Podest_lang_BK/Gelaender_Be/Stange_1950", 
				},                                                                     
				{	                                                            
					targetIndex			= "Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_U", 
					index				= "Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_lang_RE (4)/Podest_lang_BK/Gelaender_Be/Stange_1950 (1)", 
				},
			},
		},
		{ --TR12
			prefab				= "$ropeways/D-Line/supports/Robas_neu>Roba_TR_12",
			balancers			= {
				{	index		= "Wippe_12T",																					averageScale	= 1				},
				{	index		= "Wippe_12T/Wippe_12T1_LOD0",								deflectionScale	= -0.19												},
				{	index		= "Wippe_12T/Wippe_12T1_LOD0/Wippe_04T",					deflectionScale	= -0.14												},
				{	index		= "Wippe_12T/Wippe_12T1_LOD0/Wippe_04T/Wippe_02T",			deflectionScale	= -0.12												},
				{	index		= "Wippe_12T/Wippe_12T1_LOD0/Wippe_04T/Wippe_02T (1)",		deflectionScale	=  0.12												},
				{	index		= "Wippe_12T/Wippe_12T1_LOD0/Wippe_02T",					deflectionScale	=  0.12												},
				{	index		= "Wippe_12T/Wippe_12T2_LOD0",								deflectionScale	=  0.19												},
				{	index		= "Wippe_12T/Wippe_12T2_LOD0/Wippe_02T",					deflectionScale	= -0.12												},
				{	index		= "Wippe_12T/Wippe_12T2_LOD0/Wippe_04T",					deflectionScale	=  0.14												},
				{	index		= "Wippe_12T/Wippe_12T2_LOD0/Wippe_04T/Wippe_02T",			deflectionScale	= -0.12												},
				{	index		= "Wippe_12T/Wippe_12T2_LOD0/Wippe_04T/Wippe_02T (1)",		deflectionScale	=  0.12												},
				
				{	index		= "Wartungspodest_Lang_5/Podeste_5P_LI", 					deflectionScale	=  0.5,				averageScale	= 1				},
				{	index		= "Wartungspodest_Lang_5/Podeste_5P_RE", 					deflectionScale	=  0.5,				averageScale	= -1			},
			}, 
			marshallerA			= "MarshallerA",
			marshallers			= { 
				"Wippe_12T/Wippe_12T1_LOD0/Wippe_04T/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_12T/Wippe_12T1_LOD0/Wippe_04T/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_12T/Wippe_12T1_LOD0/Wippe_04T/Wippe_02T (1)/Wippe_02T_MarshallerC_01", 
				"Wippe_12T/Wippe_12T1_LOD0/Wippe_04T/Wippe_02T (1)/Wippe_02T_MarshallerC_02", 
				"Wippe_12T/Wippe_12T1_LOD0/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_12T/Wippe_12T1_LOD0/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_12T/Wippe_12T2_LOD0/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_12T/Wippe_12T2_LOD0/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_12T/Wippe_12T2_LOD0/Wippe_04T/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_12T/Wippe_12T2_LOD0/Wippe_04T/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_12T/Wippe_12T2_LOD0/Wippe_04T/Wippe_02T (1)/Wippe_02T_MarshallerC_01", 
				"Wippe_12T/Wippe_12T2_LOD0/Wippe_04T/Wippe_02T (1)/Wippe_02T_MarshallerC_02", 
			},
			animated			= {
				{	index		= "Wippe_12T/Wippe_12T1_LOD0/Wippe_04T/Wippe_02T/Rolle",				axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_12T/Wippe_12T1_LOD0/Wippe_04T/Wippe_02T/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_12T/Wippe_12T1_LOD0/Wippe_04T/Wippe_02T (1)/Rolle",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_12T/Wippe_12T1_LOD0/Wippe_04T/Wippe_02T (1)/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_12T/Wippe_12T1_LOD0/Wippe_02T/Rolle",							axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_12T/Wippe_12T1_LOD0/Wippe_02T/Rolle (1)",						axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_12T/Wippe_12T2_LOD0/Wippe_02T/Rolle",							axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_12T/Wippe_12T2_LOD0/Wippe_02T/Rolle (1)",						axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_12T/Wippe_12T2_LOD0/Wippe_04T/Wippe_02T/Rolle",				axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_12T/Wippe_12T2_LOD0/Wippe_04T/Wippe_02T/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_12T/Wippe_12T2_LOD0/Wippe_04T/Wippe_02T (1)/Rolle",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_12T/Wippe_12T2_LOD0/Wippe_04T/Wippe_02T (1)/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
			}, 
			platforms			= { 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (1)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (2)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (3)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_lang_LI (4)/Podest_lang_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_lang_LI (5)/Podest_lang_BK", 
											
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (1)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (2)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (3)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_lang_RE (4)/Podest_lang_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_lang_RE (5)/Podest_lang_BK", 
									
					"Wartungspodest_Lang_5/Podest_kurz_BK", 
			},
			
			onlyActiveWhenRight	= { "Wartungspodest_Lang_5/Halter_lang/Leiter_lang", 		},
			onlyActiveWhenLeft	= { "Wartungspodest_Lang_5/Halter_lang/Leiter_lang (1)", 	},
			
			rotateToTarget		= {
				{	
					targetIndex			= "Wartungspodest_Lang_5/Strebenhalter_oben/Streben_LI", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_LI/Strebe_5P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Lang_5/Podeste_5P_LI/Strebe_5P_1/Strebe_5P_2", 
					pistonIndex 		= "Wartungspodest_Lang_5/Podeste_5P_LI/Strebe_5P_1/Strebe_5P_3",
				},                                        
				{	                                      
					targetIndex			= "Wartungspodest_Lang_5/Strebenhalter_oben/Streben_RE", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_RE/Strebe_5P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Lang_5/Podeste_5P_RE/Strebe_5P_1/Strebe_5P_2", 
					pistonIndex 		= "Wartungspodest_Lang_5/Podeste_5P_RE/Strebe_5P_1/Strebe_5P_3",
				},                                                       
				{	                                                     
					targetIndex			= "Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_O", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_LI/Podest_lang_LI (5)/Podest_lang_BK/Gelaender_Be/Stange_2600", 
				},                                                       
				{	                                                     
					targetIndex			= "Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_U", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_LI/Podest_lang_LI (5)/Podest_lang_BK/Gelaender_Be/Stange_2600 (1)", 
				},                                                       
				{	                                                       
					targetIndex			= "Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_O", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_RE/Podest_lang_RE (5)/Podest_lang_BK/Gelaender_Be/Stange_2600", 
				},                                                        
				{	                                                    
					targetIndex			= "Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_U", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_RE/Podest_lang_RE (5)/Podest_lang_BK/Gelaender_Be/Stange_2600 (1)", 
				},
			},
		},
		{ --TR16
			prefab				= "$ropeways/D-Line/supports/Robas_neu>Roba_TR_16", 
			balancers			= {
				{	index		= "Wippe_16T",																					averageScale	= 1			},
				{	index		= "Wippe_16T/Wippe_08T",										deflectionScale	= -0.25										},
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T",								deflectionScale	= -0.125									},
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T (1)",							deflectionScale	=  0.125									},
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T/Wippe_02T",					deflectionScale	= -0.0625									},
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T/Wippe_02T (1)",				deflectionScale	=  0.0625									},
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T (1)/Wippe_02T",				deflectionScale	= -0.0625									},
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T (1)/Wippe_02T (1)",			deflectionScale	=  0.0625									},
				{	index		= "Wippe_16T/Wippe_08T (1)",									deflectionScale	=  0.25										},
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T",							deflectionScale	= -0.125									},
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T (1)",						deflectionScale	=  0.125									},
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T/Wippe_02T",				deflectionScale	= -0.0625									},
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T/Wippe_02T (1)",			deflectionScale	=  0.0625									},
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T (1)/Wippe_02T",			deflectionScale	= -0.0625									},
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T (1)/Wippe_02T (1)",		deflectionScale	=  0.0625									},
						
				{	index		= "Wartungspodest_Lang_7/Podeste_7P_LI", 						deflectionScale	=  0.5,			averageScale	= 1			},
				{	index		= "Wartungspodest_Lang_7/Podeste_7P_RE", 						deflectionScale	=  0.5,			averageScale	= -1		},
			}, 
			marshallerA			= "MarshallerA",
			marshallers			= { 
				"Wippe_16T/Wippe_08T/Wippe_04T/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_16T/Wippe_08T/Wippe_04T/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_16T/Wippe_08T/Wippe_04T/Wippe_02T (1)/Wippe_02T_MarshallerC_01", 
				"Wippe_16T/Wippe_08T/Wippe_04T/Wippe_02T (1)/Wippe_02T_MarshallerC_02", 
				"Wippe_16T/Wippe_08T/Wippe_04T (1)/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_16T/Wippe_08T/Wippe_04T (1)/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_16T/Wippe_08T/Wippe_04T (1)/Wippe_02T (1)/Wippe_02T_MarshallerC_01", 
				"Wippe_16T/Wippe_08T/Wippe_04T (1)/Wippe_02T (1)/Wippe_02T_MarshallerC_02", 
				"Wippe_16T/Wippe_08T (1)/Wippe_04T/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_16T/Wippe_08T (1)/Wippe_04T/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_16T/Wippe_08T (1)/Wippe_04T/Wippe_02T (1)/Wippe_02T_MarshallerC_01", 
				"Wippe_16T/Wippe_08T (1)/Wippe_04T/Wippe_02T (1)/Wippe_02T_MarshallerC_02", 
				"Wippe_16T/Wippe_08T (1)/Wippe_04T (1)/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_16T/Wippe_08T (1)/Wippe_04T (1)/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_16T/Wippe_08T (1)/Wippe_04T (1)/Wippe_02T (1)/Wippe_02T_MarshallerC_01", 
				"Wippe_16T/Wippe_08T (1)/Wippe_04T (1)/Wippe_02T (1)/Wippe_02T_MarshallerC_02", 
				},
			animated			= {
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T/Wippe_02T/Rolle",					axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T/Wippe_02T/Rolle (1)",				axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T/Wippe_02T (1)/Rolle",				axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T/Wippe_02T (1)/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T (1)/Wippe_02T/Rolle",				axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T (1)/Wippe_02T/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T (1)/Wippe_02T (1)/Rolle",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T/Wippe_04T (1)/Wippe_02T (1)/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T/Wippe_02T/Rolle",				axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T/Wippe_02T/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T/Wippe_02T (1)/Rolle",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T/Wippe_02T (1)/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T (1)/Wippe_02T/Rolle",			axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T (1)/Wippe_02T/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T (1)/Wippe_02T (1)/Rolle",		axis = 1,	diam	= 0.45,		scale	= 1.0 },
				{	index		= "Wippe_16T/Wippe_08T (1)/Wippe_04T (1)/Wippe_02T (1)/Rolle (1)",	axis = 1,	diam	= 0.45,		scale	= 1.0 },
			},
			platforms			= { 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (1)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (2)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (3)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (4)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (5)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_lang_LI (6)/Podest_lang_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_lang_LI (7)/Podest_lang_BK", 
												  
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (1)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (2)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (3)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (4)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (5)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_lang_RE (6)/Podest_lang_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_lang_RE (7)/Podest_lang_BK", 
									
					"Wartungspodest_Lang_7/Podest_kurz_BK", 
			},
			
			onlyActiveWhenRight	= { "Wartungspodest_Lang_7/Halter_lang/Leiter_lang", 		},
			onlyActiveWhenLeft	= { "Wartungspodest_Lang_7/Halter_lang/Leiter_lang (1)", 	},
			
			rotateToTarget		= {
				{	
					targetIndex			= "Wartungspodest_Lang_7/Strebenhalter_oben/Streben_LI", 
					index				= "Wartungspodest_Lang_7/Podeste_7P_LI/Strebe_7P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Lang_7/Podeste_7P_LI/Strebe_7P_1/Strebe_7P_2", 
					pistonIndex 		= "Wartungspodest_Lang_7/Podeste_7P_LI/Strebe_7P_1/Strebe_7P_3",
				},                                                       
				{	                                                     
					targetIndex			= "Wartungspodest_Lang_7/Strebenhalter_oben/Streben_RE",
					index				= "Wartungspodest_Lang_7/Podeste_7P_RE/Strebe_7P_1",
					pistonMiddleIndex 	= "Wartungspodest_Lang_7/Podeste_7P_RE/Strebe_7P_1/Strebe_7P_2", 
					pistonIndex 		= "Wartungspodest_Lang_7/Podeste_7P_RE/Strebe_7P_1/Strebe_7P_3",
				},                                            
				{	                                          
					targetIndex			= "Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_O", 
					index				= "Wartungspodest_Lang_7/Podeste_7P_LI/Podest_lang_LI (7)/Podest_lang_BK/Gelaender_Be/Stange_3900", 
				},                                             
				{	                                           
					targetIndex			= "Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_U", 
					index				= "Wartungspodest_Lang_7/Podeste_7P_LI/Podest_lang_LI (7)/Podest_lang_BK/Gelaender_Be/Stange_3900 (1)", 
				},                                            
				{	                                          
					targetIndex			= "Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_O", 
					index				= "Wartungspodest_Lang_7/Podeste_7P_RE/Podest_lang_RE (7)/Podest_lang_BK/Gelaender_Be/Stange_3900", 
				},                                           
				{	                                         
					targetIndex			= "Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_U", 
					index				= "Wartungspodest_Lang_7/Podeste_7P_RE/Podest_lang_RE (7)/Podest_lang_BK/Gelaender_Be/Stange_3900 (1)", 
				},
			},
		},
		{ --WL04
			prefab				= "$ropeways/D-Line/supports/Robas_neu>Roba_WL_04",
			balancers			= {
				{	index		= "Wippe_04W_s",																	averageScale	= 1			},
				{	index		= "Wippe_04W_s/Wippe_04W/WL_OR_LOD0",				deflectionScale	= -0.05										},
				{	index		= "Wippe_04W_s/Wippe_04W/WL_OR_LOD0/Wippe_02N",		deflectionScale	= -0.20										},
				{	index		= "Wippe_04W_s/Wippe_04W/WL_OL_LOD0",				deflectionScale	=  0.05										},
				{	index		= "Wippe_04W_s/Wippe_04W/WL_OL_LOD0/Wippe_02N",		deflectionScale	=  0.20										},
				{	index		= "Wippe_04W_s/Wippe_04W/WL_UR_LOD0",				deflectionScale	= -0.05										},
				{	index		= "Wippe_04W_s/Wippe_04W/WL_UR_LOD0/Wippe_02T",		deflectionScale	= -0.20										},
				{	index		= "Wippe_04W_s/Wippe_04W/WL_UL_LOD0",				deflectionScale	=  0.05										},
				{	index		= "Wippe_04W_s/Wippe_04W/WL_UL_LOD0/Wippe_02T",		deflectionScale	=  0.20										},
				
				{	index		= "Wartungspodest_Lang_3/Podeste_3P_LI", 			deflectionScale	=  0.5,			averageScale	= 1			},
				{	index		= "Wartungspodest_Lang_3/Podeste_3P_RE", 			deflectionScale	=  0.5,			averageScale	= -1		},
			},
			marshallerA			= "MarshallerA",
			marshallers			= { 
				"Wippe_04W_s/Wippe_04W/WL_OR_LOD0/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_04W_s/Wippe_04W/WL_UR_LOD0/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_04W_s/Wippe_04W/WL_UL_LOD0/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_04W_s/Wippe_04W/WL_OL_LOD0/Wippe_02N/Wippe_02N_MarshallerC_02" 
			},
			animated			= {
				{	index		= "Wippe_04W_s/Wippe_04W/WL_OR_LOD0/Wippe_02N/Rolle",		axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_04W_s/Wippe_04W/WL_OR_LOD0/Wippe_02N/Rolle (1)",	axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_04W_s/Wippe_04W/WL_OL_LOD0/Wippe_02N/Rolle",		axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_04W_s/Wippe_04W/WL_OL_LOD0/Wippe_02N/Rolle (1)",	axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_04W_s/Wippe_04W/WL_UR_LOD0/Wippe_02T/Rolle",		axis = 1,	diam	= 0.45,		scale	=  1.0 },
				{	index		= "Wippe_04W_s/Wippe_04W/WL_UR_LOD0/Wippe_02T/Rolle (1)",	axis = 1,	diam	= 0.45,		scale	=  1.0 },
				{	index		= "Wippe_04W_s/Wippe_04W/WL_UL_LOD0/Wippe_02T/Rolle",		axis = 1,	diam	= 0.45,		scale	=  1.0 },
				{	index		= "Wippe_04W_s/Wippe_04W/WL_UL_LOD0/Wippe_02T/Rolle (1)",	axis = 1,	diam	= 0.45,		scale	=  1.0 },
			},
			platforms			= { 
					"Wartungspodest_Lang_3/Podeste_3P_LI/Podest_lang_LI (1)/Podest_lang_BK", 
					"Wartungspodest_Lang_3/Podeste_3P_LI/Podest_lang_LI (2)/Podest_lang_BK", 
					"Wartungspodest_Lang_3/Podeste_3P_LI/Podest_lang_LI (3)/Podest_lang_BK", 
					
					"Wartungspodest_Lang_3/Podeste_3P_RE/Podest_lang_RE (1)/Podest_lang_BK", 
					"Wartungspodest_Lang_3/Podeste_3P_RE/Podest_lang_RE (2)/Podest_lang_BK", 
					"Wartungspodest_Lang_3/Podeste_3P_RE/Podest_lang_RE (3)/Podest_lang_BK", 
					
					"Wartungspodest_Lang_3/Podest_lang_BK", 
			},
			
			onlyActiveWhenRight	= { "Wartungspodest_Lang_3/Halter_lang/Leiter_lang", 		},
			onlyActiveWhenLeft	= { "Wartungspodest_Lang_3/Halter_lang/Leiter_lang (1)", 	},
			
			rotateToTarget		= {
				{	
					targetIndex			= "Wartungspodest_Lang_3/Strebenhalter_oben/Streben_LI", 
					index				= "Wartungspodest_Lang_3/Podeste_3P_LI/Strebe_3P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Lang_3/Podeste_3P_LI/Strebe_3P_1/Strebe_3P_2", 
					pistonIndex 		= "Wartungspodest_Lang_3/Podeste_3P_LI/Strebe_3P_1/Strebe_3P_3",
				},                                        
				{	                                      
					targetIndex			= "Wartungspodest_Lang_3/Strebenhalter_oben/Streben_RE", 
					index				= "Wartungspodest_Lang_3/Podeste_3P_RE/Strebe_3P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Lang_3/Podeste_3P_RE/Strebe_3P_1/Strebe_3P_2", 
					pistonIndex 		= "Wartungspodest_Lang_3/Podeste_3P_RE/Strebe_3P_1/Strebe_3P_3",
				},                                       
				{	                                     
					targetIndex			= "Wartungspodest_Lang_3/Podeste_3P_LI/Podest_lang_LI (1)/Podest_lang_BK/Gelaender_Li/Target_O", 
					index				= "Wartungspodest_Lang_3/Podeste_3P_LI/Podest_lang_LI (3)/Podest_lang_BK/Gelaender_Be/Stange_1300", 
				},                                        
				{	                                      
					targetIndex			= "Wartungspodest_Lang_3/Podeste_3P_LI/Podest_lang_LI (1)/Podest_lang_BK/Gelaender_Li/Target_U", 
					index				= "Wartungspodest_Lang_3/Podeste_3P_LI/Podest_lang_LI (3)/Podest_lang_BK/Gelaender_Be/Stange_1300 (1)", 
				},                                        
				{	                                      
					targetIndex			= "Wartungspodest_Lang_3/Podeste_3P_RE/Podest_lang_RE (1)/Podest_lang_BK/Gelaender_Re/Target_O", 
					index				= "Wartungspodest_Lang_3/Podeste_3P_RE/Podest_lang_RE (3)/Podest_lang_BK/Gelaender_Be/Stange_1300", 
				},                                       
				{	                                     
					targetIndex			= "Wartungspodest_Lang_3/Podeste_3P_RE/Podest_lang_RE (1)/Podest_lang_BK/Gelaender_Re/Target_U", 
					index				= "Wartungspodest_Lang_3/Podeste_3P_RE/Podest_lang_RE (3)/Podest_lang_BK/Gelaender_Be/Stange_1300 (1)", 
				},
			},
		},
		{ --WL08
			prefab				= "$ropeways/D-Line/supports/Robas_neu>Roba_WL_08", 
			balancers			= {
				{	index		= "Wippe_08W",																					averageScale	= 1			},
				{	index		= "Wippe_08W/Wippe_04W_k",										deflectionScale	= -0.25										},
				{	index		= "Wippe_08W/Wippe_04W_k (1)",									deflectionScale	=  0.25										},
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_OR_LOD0",					deflectionScale	= -0.025									},
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_OL_LOD0",					deflectionScale	=  0.025									},
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_UR_LOD0",					deflectionScale	= -0.025									},
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_UL_LOD0",					deflectionScale	=  0.025									},
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_OR_LOD0",				deflectionScale	= -0.025									},
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_OL_LOD0",				deflectionScale	=  0.025									},
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_UR_LOD0",				deflectionScale	= -0.025									},
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_UL_LOD0",				deflectionScale	=  0.025									},
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_OR_LOD0/Wippe_02N",		deflectionScale	= -0.1										},
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_OL_LOD0/Wippe_02N",		deflectionScale	=  0.1										},
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_UR_LOD0/Wippe_02T",		deflectionScale	= -0.1										},
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_UL_LOD0/Wippe_02T",		deflectionScale	=  0.1										},
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_OR_LOD0/Wippe_02N",	deflectionScale	= -0.1										},
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_OL_LOD0/Wippe_02N",	deflectionScale	=  0.1										},
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_UR_LOD0/Wippe_02T",	deflectionScale	= -0.1										},
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_UL_LOD0/Wippe_02T",	deflectionScale	=  0.1										},
				
				{	index		= "Wartungspodest_Lang_5/Podeste_5P_LI", 						deflectionScale	=  0.5,			averageScale	= 1			},
				{	index		= "Wartungspodest_Lang_5/Podeste_5P_RE", 						deflectionScale	=  0.5,			averageScale	= -1		},
			},
			marshallerA			= "MarshallerA",
			marshallers			= { 
				"Wippe_08W/Wippe_04W_k/Wippe_04W/WL_OR_LOD0/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_08W/Wippe_04W_k/Wippe_04W/WL_UR_LOD0/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_08W/Wippe_04W_k/Wippe_04W/WL_UL_LOD0/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_08W/Wippe_04W_k/Wippe_04W/WL_OL_LOD0/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_OR_LOD0/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_UR_LOD0/Wippe_02T/Wippe_02T_MarshallerC_02", 
				"Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_UL_LOD0/Wippe_02T/Wippe_02T_MarshallerC_01", 
				"Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_OL_LOD0/Wippe_02N/Wippe_02N_MarshallerC_02" 
			},
			animated			= {
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_OR_LOD0/Wippe_02N/Rolle",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_OR_LOD0/Wippe_02N/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_OL_LOD0/Wippe_02N/Rolle",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_OL_LOD0/Wippe_02N/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_UR_LOD0/Wippe_02T/Rolle",				axis = 1,	diam	= 0.45,		scale	=  1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_UR_LOD0/Wippe_02T/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	=  1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_UL_LOD0/Wippe_02T/Rolle",				axis = 1,	diam	= 0.45,		scale	=  1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k/Wippe_04W/WL_UL_LOD0/Wippe_02T/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	=  1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_OR_LOD0/Wippe_02N/Rolle",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_OR_LOD0/Wippe_02N/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_OL_LOD0/Wippe_02N/Rolle",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_OL_LOD0/Wippe_02N/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_UR_LOD0/Wippe_02T/Rolle",			axis = 1,	diam	= 0.45,		scale	=  1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_UR_LOD0/Wippe_02T/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	=  1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_UL_LOD0/Wippe_02T/Rolle",			axis = 1,	diam	= 0.45,		scale	=  1.0 },
				{	index		= "Wippe_08W/Wippe_04W_k (1)/Wippe_04W/WL_UL_LOD0/Wippe_02T/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	=  1.0 },
			},
			platforms			= { 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (1)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (2)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (3)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_lang_LI (4)/Podest_lang_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_lang_LI (5)/Podest_lang_BK", 
											
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (1)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (2)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (3)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_lang_RE (4)/Podest_lang_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_lang_RE (5)/Podest_lang_BK", 
									
					"Wartungspodest_Lang_5/Podest_kurz_BK", 
			},
			
			onlyActiveWhenRight	= { "Wartungspodest_Lang_5/Halter_lang/Leiter_lang", 		},
			onlyActiveWhenLeft	= { "Wartungspodest_Lang_5/Halter_lang/Leiter_lang (1)", 	},
			
			rotateToTarget		= {
				{	
					targetIndex			= "Wartungspodest_Lang_5/Strebenhalter_oben/Streben_LI", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_LI/Strebe_5P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Lang_5/Podeste_5P_LI/Strebe_5P_1/Strebe_5P_2", 
					pistonIndex 		= "Wartungspodest_Lang_5/Podeste_5P_LI/Strebe_5P_1/Strebe_5P_3",
				},                                        
				{	                                      
					targetIndex			= "Wartungspodest_Lang_5/Strebenhalter_oben/Streben_RE", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_RE/Strebe_5P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Lang_5/Podeste_5P_RE/Strebe_5P_1/Strebe_5P_2", 
					pistonIndex 		= "Wartungspodest_Lang_5/Podeste_5P_RE/Strebe_5P_1/Strebe_5P_3",
				},                                                       
				{	                                                     
					targetIndex			= "Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_O", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_LI/Podest_lang_LI (5)/Podest_lang_BK/Gelaender_Be/Stange_2600", 
				},                                                       
				{	                                                     
					targetIndex			= "Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_U", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_LI/Podest_lang_LI (5)/Podest_lang_BK/Gelaender_Be/Stange_2600 (1)", 
				},                                                       
				{	                                                       
					targetIndex			= "Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_O", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_RE/Podest_lang_RE (5)/Podest_lang_BK/Gelaender_Be/Stange_2600", 
				},                                                        
				{	                                                    
					targetIndex			= "Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_U", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_RE/Podest_lang_RE (5)/Podest_lang_BK/Gelaender_Be/Stange_2600 (1)", 
				},
			},
		},
		{ --NH06
			prefab				= "$ropeways/D-Line/supports/Robas_neu>Roba_NH_06", 
			balancers			= {
				{	index		= "Wippe_06N",																		averageScale	= 1 		},
				{	index		= "Wippe_06N/Wippe_02N",							deflectionScale	= -0.24										},
				{	index		= "Wippe_06N/Wippe_04N/Wippe_02N",					deflectionScale	= -0.24										},
				{	index		= "Wippe_06N/Wippe_04N/Wippe_02N (1)",				deflectionScale	=  0.24										},
				{	index		= "Wippe_06N/Wippe_04N",							deflectionScale	=  0.28										},
				
				{	index		= "Wartungspodest_Mittel_3/Podeste_3P_LI", 			deflectionScale	=  0.5,			averageScale	= 1			},
				{	index		= "Wartungspodest_Mittel_3/Podeste_3P_RE", 			deflectionScale	=  0.5,			averageScale	= -1		},
			},
			marshallerA			= "MarshallerA",
			marshallers			= { 
				"Wippe_06N/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_06N/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_06N/Wippe_04N/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_06N/Wippe_04N/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_06N/Wippe_04N/Wippe_02N (1)/Wippe_02N_MarshallerC_01", 
				"Wippe_06N/Wippe_04N/Wippe_02N (1)/Wippe_02N_MarshallerC_02", 
			},
			animated			= {
				{	index		= "Wippe_06N/Wippe_02N/Rolle",						axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_06N/Wippe_02N/Rolle (1)",					axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_06N/Wippe_04N/Wippe_02N/Rolle",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_06N/Wippe_04N/Wippe_02N/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_06N/Wippe_04N/Wippe_02N (1)/Rolle",		axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_06N/Wippe_04N/Wippe_02N (1)/Rolle (1)",	axis = 1,	diam	= 0.45,		scale	= -1.0 },
			},
			platforms			= { 
					"Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (1)/Podest_lang_BK", 
					"Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (2)/Podest_lang_BK", 
					"Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (3)/Podest_lang_BK", 
					
					"Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (1)/Podest_lang_BK", 
					"Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (2)/Podest_lang_BK", 
					"Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (3)/Podest_lang_BK", 
					
					"Wartungspodest_Mittel_3/Podest_lang_BK", 
			}, 
			
			onlyActiveWhenRight	= { "Wartungspodest_Mittel_3/Halter_mittel/Leiter_mittel", 		},
			onlyActiveWhenLeft	= { "Wartungspodest_Mittel_3/Halter_mittel/Leiter_mittel (1)", 	},
			
			rotateToTarget		= {
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Strebenhalter_oben/Streben_LI", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_LI/Strebe_3P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Mittel_3/Podeste_3P_LI/Strebe_3P_1/Strebe_3P_2", 
					pistonIndex 		= "Wartungspodest_Mittel_3/Podeste_3P_LI/Strebe_3P_1/Strebe_3P_3",
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Strebenhalter_oben/Streben_RE", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_RE/Strebe_3P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Mittel_3/Podeste_3P_RE/Strebe_3P_1/Strebe_3P_2", 
					pistonIndex 		= "Wartungspodest_Mittel_3/Podeste_3P_RE/Strebe_3P_1/Strebe_3P_3",
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (1)/Podest_lang_BK/Gelaender_Li/Target_O", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (3)/Podest_lang_BK/Gelaender_Be/Stange_1300", 
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (1)/Podest_lang_BK/Gelaender_Li/Target_U", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_LI/Podest_lang_LI (3)/Podest_lang_BK/Gelaender_Be/Stange_1300 (1)", 
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (1)/Podest_lang_BK/Gelaender_Re/Target_O", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (3)/Podest_lang_BK/Gelaender_Be/Stange_1300", 
				},
				{	
					targetIndex			= "Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (1)/Podest_lang_BK/Gelaender_Re/Target_U", 
					index				= "Wartungspodest_Mittel_3/Podeste_3P_RE/Podest_lang_RE (3)/Podest_lang_BK/Gelaender_Be/Stange_1300 (1)", 
				},
			},
		},
		{ --NH08
			prefab				= "$ropeways/D-Line/supports/Robas_neu>Roba_NH_08",
			balancers			= {
				{	index		= "Wippe_08N_s",																		averageScale	= 1			},
				{	index		= "Wippe_08N_s/Wippe_04N",						deflectionScale	= -0.25												},
				{	index		= "Wippe_08N_s/Wippe_04N (1)",					deflectionScale	=  0.25												},
				{	index		= "Wippe_08N_s/Wippe_04N/Wippe_02N",			deflectionScale	=  -0.125											},
				{	index		= "Wippe_08N_s/Wippe_04N/Wippe_02N (1)",		deflectionScale	=  0.125											},
				{	index		= "Wippe_08N_s/Wippe_04N (1)/Wippe_02N",		deflectionScale	=  -0.125											},
				{	index		= "Wippe_08N_s/Wippe_04N (1)/Wippe_02N (1)",	deflectionScale	=  0.125											},
				
				{	index		= "Wartungspodest_Mittel_4/Podeste_4P_LI", 				deflectionScale	=  0.5,			averageScale	= 1			},
				{	index		= "Wartungspodest_Mittel_4/Podeste_4P_RE", 				deflectionScale	=  0.5,			averageScale	= -1		},
			},
			marshallerA			= "MarshallerA",
			marshallers			= { 
				"Wippe_08N_s/Wippe_04N/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_08N_s/Wippe_04N/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_08N_s/Wippe_04N/Wippe_02N (1)/Wippe_02N_MarshallerC_01", 
				"Wippe_08N_s/Wippe_04N/Wippe_02N (1)/Wippe_02N_MarshallerC_02", 
				"Wippe_08N_s/Wippe_04N (1)/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_08N_s/Wippe_04N (1)/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_08N_s/Wippe_04N (1)/Wippe_02N (1)/Wippe_02N_MarshallerC_01", 
				"Wippe_08N_s/Wippe_04N (1)/Wippe_02N (1)/Wippe_02N_MarshallerC_02" 
			},
			animated			= {
				{	index		= "Wippe_08N_s/Wippe_04N/Wippe_02N/Rolle",					axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08N_s/Wippe_04N/Wippe_02N/Rolle (1)",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08N_s/Wippe_04N/Wippe_02N (1)/Rolle",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08N_s/Wippe_04N/Wippe_02N (1)/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08N_s/Wippe_04N (1)/Wippe_02N/Rolle",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08N_s/Wippe_04N (1)/Wippe_02N/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08N_s/Wippe_04N (1)/Wippe_02N (1)/Rolle",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_08N_s/Wippe_04N (1)/Wippe_02N (1)/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= -1.0 },
			},
			platforms			= { 
					"Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_kurz_LI (1)/Podest_kurz_BK", 
					"Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_kurz_LI (2)/Podest_kurz_BK", 
					"Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_lang_LI (3)/Podest_lang_BK", 
					"Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_lang_LI (4)/Podest_lang_BK", 
					
					"Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_kurz_RE (1)/Podest_kurz_BK", 
					"Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_kurz_RE (2)/Podest_kurz_BK", 
					"Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_lang_RE (3)/Podest_lang_BK", 
					"Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_lang_RE (4)/Podest_lang_BK", 
					
					"Wartungspodest_Mittel_4/Podest_kurz_BK", 
			}, 
			
			onlyActiveWhenRight	= { "Wartungspodest_Mittel_4/Halter_mittel/Leiter_mittel", 		},
			onlyActiveWhenLeft	= { "Wartungspodest_Mittel_4/Halter_mittel/Leiter_mittel (1)", 	},	

			rotateToTarget		= {
				{	
					targetIndex			= "Wartungspodest_Mittel_4/Strebenhalter_oben/Streben_LI", 
					index				= "Wartungspodest_Mittel_4/Podeste_4P_LI/Strebe_4P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Mittel_4/Podeste_4P_LI/Strebe_4P_1/Strebe_4P_2", 
					pistonIndex 		= "Wartungspodest_Mittel_4/Podeste_4P_LI/Strebe_4P_1/Strebe_4P_3",
				},                                               
				{	                                             
					targetIndex			= "Wartungspodest_Mittel_4/Strebenhalter_oben/Streben_RE", 
					index				= "Wartungspodest_Mittel_4/Podeste_4P_RE/Strebe_4P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Mittel_4/Podeste_4P_RE/Strebe_4P_1/Strebe_4P_2", 
					pistonIndex 		= "Wartungspodest_Mittel_4/Podeste_4P_RE/Strebe_4P_1/Strebe_4P_3",
				},                                               
				{	                                          
					targetIndex			= "Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_O", 
					index				= "Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_lang_LI (4)/Podest_lang_BK/Gelaender_Be/Stange_1950", 
				},                                                                 
				{	                                                            
					targetIndex			= "Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_U", 
					index				= "Wartungspodest_Mittel_4/Podeste_4P_LI/Podest_lang_LI (4)/Podest_lang_BK/Gelaender_Be/Stange_1950 (1)", 
				},                                                             
				{	                                                                  
					targetIndex			= "Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_O", 
					index				= "Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_lang_RE (4)/Podest_lang_BK/Gelaender_Be/Stange_1950", 
				},                                                                     
				{	                                                            
					targetIndex			= "Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_U", 
					index				= "Wartungspodest_Mittel_4/Podeste_4P_RE/Podest_lang_RE (4)/Podest_lang_BK/Gelaender_Be/Stange_1950 (1)", 
				},
			},
		},
		{ --NH12
			prefab				= "$ropeways/D-Line/supports/Robas_neu>Roba_NH_12",
			balancers			= {
				{	index		= "Wippe_12N",												deflectionScale	=  0,			averageScale	= 1			},
				{	index		= "Wippe_12N/Wippe_12N1_LOD0",								deflectionScale	= -0.19										},
				{	index		= "Wippe_12N/Wippe_12N1_LOD0/Wippe_04N",					deflectionScale	= -0.14										},
				{	index		= "Wippe_12N/Wippe_12N1_LOD0/Wippe_04N/Wippe_02N",			deflectionScale	= -0.12										},
				{	index		= "Wippe_12N/Wippe_12N1_LOD0/Wippe_04N/Wippe_02N (1)",		deflectionScale	=  0.12										},
				{	index		= "Wippe_12N/Wippe_12N1_LOD0/Wippe_02N",					deflectionScale	=  0.12										},
				{	index		= "Wippe_12N/Wippe_12N2_LOD0",								deflectionScale	=  0.19										},
				{	index		= "Wippe_12N/Wippe_12N2_LOD0/Wippe_02N",					deflectionScale	= -0.12										},
				{	index		= "Wippe_12N/Wippe_12N2_LOD0/Wippe_04N",					deflectionScale	=  0.14										},
				{	index		= "Wippe_12N/Wippe_12N2_LOD0/Wippe_04N/Wippe_02N",			deflectionScale	= -0.12										},
				{	index		= "Wippe_12N/Wippe_12N2_LOD0/Wippe_04N/Wippe_02N (1)",		deflectionScale	=  0.12										},
				
				{	index		= "Spanner/Spanner_LOD0",									deflectionScale	=  0,			averageScale	= 0.65		},
				
				{	index		= "Wartungspodest_Lang_5/Podeste_5P_LI", 					deflectionScale	=  0.5,			averageScale	= 1			},
				{	index		= "Wartungspodest_Lang_5/Podeste_5P_RE", 					deflectionScale	=  0.5,			averageScale	= -1		},
			},
			marshallerA			= "MarshallerA",
			marshallers			= { 
				"Wippe_12N/Wippe_12N1_LOD0/Wippe_04N/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_12N/Wippe_12N1_LOD0/Wippe_04N/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_12N/Wippe_12N1_LOD0/Wippe_04N/Wippe_02N (1)/Wippe_02N_MarshallerC_01", 
				"Wippe_12N/Wippe_12N1_LOD0/Wippe_04N/Wippe_02N (1)/Wippe_02N_MarshallerC_02", 
				"Wippe_12N/Wippe_12N1_LOD0/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_12N/Wippe_12N1_LOD0/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_12N/Wippe_12N2_LOD0/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_12N/Wippe_12N2_LOD0/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_12N/Wippe_12N2_LOD0/Wippe_04N/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_12N/Wippe_12N2_LOD0/Wippe_04N/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_12N/Wippe_12N2_LOD0/Wippe_04N/Wippe_02N (1)/Wippe_02N_MarshallerC_01", 
				"Wippe_12N/Wippe_12N2_LOD0/Wippe_04N/Wippe_02N (1)/Wippe_02N_MarshallerC_02" 
			},
			animated			= {
				{	index		= "Wippe_12N/Wippe_12N1_LOD0/Wippe_04N/Wippe_02N/Rolle",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_12N/Wippe_12N1_LOD0/Wippe_04N/Wippe_02N/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_12N/Wippe_12N1_LOD0/Wippe_04N/Wippe_02N (1)/Rolle",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_12N/Wippe_12N1_LOD0/Wippe_04N/Wippe_02N (1)/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_12N/Wippe_12N1_LOD0/Wippe_02N/Rolle",							axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_12N/Wippe_12N1_LOD0/Wippe_02N/Rolle (1)",						axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_12N/Wippe_12N2_LOD0/Wippe_02N/Rolle",							axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_12N/Wippe_12N2_LOD0/Wippe_02N/Rolle (1)",						axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_12N/Wippe_12N2_LOD0/Wippe_04N/Wippe_02N/Rolle",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_12N/Wippe_12N2_LOD0/Wippe_04N/Wippe_02N/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_12N/Wippe_12N2_LOD0/Wippe_04N/Wippe_02N (1)/Rolle",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_12N/Wippe_12N2_LOD0/Wippe_04N/Wippe_02N (1)/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= -1.0 },
			},
			platforms			= { 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (1)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (2)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (3)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_lang_LI (4)/Podest_lang_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_LI/Podest_lang_LI (5)/Podest_lang_BK", 
											
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (1)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (2)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (3)/Podest_kurz_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_lang_RE (4)/Podest_lang_BK", 
					"Wartungspodest_Lang_5/Podeste_5P_RE/Podest_lang_RE (5)/Podest_lang_BK", 
									
					"Wartungspodest_Lang_5/Podest_kurz_BK", 
			}, 
			
			onlyActiveWhenRight	= { "Wartungspodest_Lang_5/Halter_lang/Leiter_lang", 		},
			onlyActiveWhenLeft	= { "Wartungspodest_Lang_5/Halter_lang/Leiter_lang (1)", 	},
			
			rotateToTarget		= {
				{	
					targetIndex			= "Wartungspodest_Lang_5/Strebenhalter_oben/Streben_LI", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_LI/Strebe_5P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Lang_5/Podeste_5P_LI/Strebe_5P_1/Strebe_5P_2", 
					pistonIndex 		= "Wartungspodest_Lang_5/Podeste_5P_LI/Strebe_5P_1/Strebe_5P_3",
				},                                        
				{	                                      
					targetIndex			= "Wartungspodest_Lang_5/Strebenhalter_oben/Streben_RE", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_RE/Strebe_5P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Lang_5/Podeste_5P_RE/Strebe_5P_1/Strebe_5P_2", 
					pistonIndex 		= "Wartungspodest_Lang_5/Podeste_5P_RE/Strebe_5P_1/Strebe_5P_3",
				},                                                       
				{	                                                     
					targetIndex			= "Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_O", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_LI/Podest_lang_LI (5)/Podest_lang_BK/Gelaender_Be/Stange_2600", 
				},                                                       
				{	                                                     
					targetIndex			= "Wartungspodest_Lang_5/Podeste_5P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_U", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_LI/Podest_lang_LI (5)/Podest_lang_BK/Gelaender_Be/Stange_2600 (1)", 
				},                                                       
				{	                                                       
					targetIndex			= "Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_O", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_RE/Podest_lang_RE (5)/Podest_lang_BK/Gelaender_Be/Stange_2600", 
				},                                                        
				{	                                                    
					targetIndex			= "Wartungspodest_Lang_5/Podeste_5P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_U", 
					index				= "Wartungspodest_Lang_5/Podeste_5P_RE/Podest_lang_RE (5)/Podest_lang_BK/Gelaender_Be/Stange_2600 (1)", 
				},
			},
		},
		{ --NH16
			prefab				= "$ropeways/D-Line/supports/Robas_neu>Roba_NH_16",
			balancers			= {
				{	index		= "Wippe_16N",																					averageScale	= 1			},
				{	index		= "Wippe_16N/Wippe_08N",										deflectionScale	= -0.25										},
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N",								deflectionScale	= -0.125									},
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N (1)",							deflectionScale	=  0.125									},
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N/Wippe_02N",					deflectionScale	= -0.0625									},
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N/Wippe_02N (1)",				deflectionScale	=  0.0625									},
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N (1)/Wippe_02N",				deflectionScale	= -0.0625									},
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N (1)/Wippe_02N (1)",			deflectionScale	=  0.0625									},
				{	index		= "Wippe_16N/Wippe_08N (1)",									deflectionScale	=  0.25										},
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N",							deflectionScale	= -0.125									},
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N (1)",						deflectionScale	=  0.125									},
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N/Wippe_02N",				deflectionScale	= -0.0625									},
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N/Wippe_02N (1)",			deflectionScale	=  0.0625									},
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N (1)/Wippe_02N",			deflectionScale	= -0.0625									},
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N (1)/Wippe_02N (1)",		deflectionScale	=  0.0625									},
				
				{	index		= "Spanner/Spanner_LOD0",																		averageScale	= 0.65		},
								
				{	index		= "Wartungspodest_Lang_7/Podeste_7P_LI", 						deflectionScale	=  0.5,			averageScale	= 1			},
				{	index		= "Wartungspodest_Lang_7/Podeste_7P_RE", 						deflectionScale	=  0.5,			averageScale	= -1		},
			},
			marshallerA			= "MarshallerA",
			marshallers			= { 
				"Wippe_16N/Wippe_08N/Wippe_04N/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_16N/Wippe_08N/Wippe_04N/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_16N/Wippe_08N/Wippe_04N/Wippe_02N (1)/Wippe_02N_MarshallerC_01", 
				"Wippe_16N/Wippe_08N/Wippe_04N/Wippe_02N (1)/Wippe_02N_MarshallerC_02", 
				"Wippe_16N/Wippe_08N/Wippe_04N (1)/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_16N/Wippe_08N/Wippe_04N (1)/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_16N/Wippe_08N/Wippe_04N (1)/Wippe_02N (1)/Wippe_02N_MarshallerC_01", 
				"Wippe_16N/Wippe_08N/Wippe_04N (1)/Wippe_02N (1)/Wippe_02N_MarshallerC_02", 
				"Wippe_16N/Wippe_08N (1)/Wippe_04N/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_16N/Wippe_08N (1)/Wippe_04N/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_16N/Wippe_08N (1)/Wippe_04N/Wippe_02N (1)/Wippe_02N_MarshallerC_01", 
				"Wippe_16N/Wippe_08N (1)/Wippe_04N/Wippe_02N (1)/Wippe_02N_MarshallerC_02", 
				"Wippe_16N/Wippe_08N (1)/Wippe_04N (1)/Wippe_02N/Wippe_02N_MarshallerC_01", 
				"Wippe_16N/Wippe_08N (1)/Wippe_04N (1)/Wippe_02N/Wippe_02N_MarshallerC_02", 
				"Wippe_16N/Wippe_08N (1)/Wippe_04N (1)/Wippe_02N (1)/Wippe_02N_MarshallerC_01", 
				"Wippe_16N/Wippe_08N (1)/Wippe_04N (1)/Wippe_02N (1)/Wippe_02N_MarshallerC_02" 
			},
			animated			= {
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N/Wippe_02N/Rolle",						axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N/Wippe_02N/Rolle (1)",					axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N/Wippe_02N (1)/Rolle",					axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N/Wippe_02N (1)/Rolle (1)",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N (1)/Wippe_02N/Rolle",					axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N (1)/Wippe_02N/Rolle (1)",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N (1)/Wippe_02N (1)/Rolle",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N/Wippe_04N (1)/Wippe_02N (1)/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N/Wippe_02N/Rolle",					axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N/Wippe_02N/Rolle (1)",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N/Wippe_02N (1)/Rolle",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N/Wippe_02N (1)/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N (1)/Wippe_02N/Rolle",				axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N (1)/Wippe_02N/Rolle (1)",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N (1)/Wippe_02N (1)/Rolle",			axis = 1,	diam	= 0.45,		scale	= -1.0 },
				{	index		= "Wippe_16N/Wippe_08N (1)/Wippe_04N (1)/Wippe_02N (1)/Rolle (1)",		axis = 1,	diam	= 0.45,		scale	= -1.0 },
			}, 
			platforms			= { 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (1)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (2)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (3)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (4)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (5)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_lang_LI (6)/Podest_lang_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_LI/Podest_lang_LI (7)/Podest_lang_BK", 
												  
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (1)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (2)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (3)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (4)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (5)/Podest_kurz_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_lang_RE (6)/Podest_lang_BK", 
					"Wartungspodest_Lang_7/Podeste_7P_RE/Podest_lang_RE (7)/Podest_lang_BK", 
									
					"Wartungspodest_Lang_7/Podest_kurz_BK", 
			}, 
			
			onlyActiveWhenRight	= { "Wartungspodest_Lang_7/Halter_lang/Leiter_lang", 		},
			onlyActiveWhenLeft	= { "Wartungspodest_Lang_7/Halter_lang/Leiter_lang (1)", 	},
			
			rotateToTarget		= {
				{	
					targetIndex			= "Wartungspodest_Lang_7/Strebenhalter_oben/Streben_LI", 
					index				= "Wartungspodest_Lang_7/Podeste_7P_LI/Strebe_7P_1", 
					pistonMiddleIndex 	= "Wartungspodest_Lang_7/Podeste_7P_LI/Strebe_7P_1/Strebe_7P_2", 
					pistonIndex 		= "Wartungspodest_Lang_7/Podeste_7P_LI/Strebe_7P_1/Strebe_7P_3",
				},                                                       
				{	                                                     
					targetIndex			= "Wartungspodest_Lang_7/Strebenhalter_oben/Streben_RE",
					index				= "Wartungspodest_Lang_7/Podeste_7P_RE/Strebe_7P_1",
					pistonMiddleIndex 	= "Wartungspodest_Lang_7/Podeste_7P_RE/Strebe_7P_1/Strebe_7P_2", 
					pistonIndex 		= "Wartungspodest_Lang_7/Podeste_7P_RE/Strebe_7P_1/Strebe_7P_3",
				},                                            
				{	                                          
					targetIndex			= "Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_O", 
					index				= "Wartungspodest_Lang_7/Podeste_7P_LI/Podest_lang_LI (7)/Podest_lang_BK/Gelaender_Be/Stange_3900", 
				},                                             
				{	                                           
					targetIndex			= "Wartungspodest_Lang_7/Podeste_7P_LI/Podest_kurz_LI (1)/Podest_kurz_BK/Gelaender_Li/Target_U", 
					index				= "Wartungspodest_Lang_7/Podeste_7P_LI/Podest_lang_LI (7)/Podest_lang_BK/Gelaender_Be/Stange_3900 (1)", 
				},                                            
				{	                                          
					targetIndex			= "Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_O", 
					index				= "Wartungspodest_Lang_7/Podeste_7P_RE/Podest_lang_RE (7)/Podest_lang_BK/Gelaender_Be/Stange_3900", 
				},                                           
				{	                                         
					targetIndex			= "Wartungspodest_Lang_7/Podeste_7P_RE/Podest_kurz_RE (1)/Podest_kurz_BK/Gelaender_Re/Target_U", 
					index				= "Wartungspodest_Lang_7/Podeste_7P_RE/Podest_lang_RE (7)/Podest_lang_BK/Gelaender_Be/Stange_3900 (1)", 
				},
			},
		},
	}
});